server:
  port: 9090

security:
  oauth2:
    client:
      client-id: clientapp
      client-secret: 112233
    resource:
      token-info-uri: http://127.0.0.1:8080/oauth/check_token
    access-token-uri: http://127.0.0.1:8080/oauth/token